---
# file : _cleanup-config.yml
# description : cleanup existing nginx config files
# source : https://github.com/nginxinc/ansible-role-nginx-config/blob/main/tasks/config/cleanup-config.yml

- name: Find NGINX config files
  ansible.builtin.find:
    paths: "{{ item['directory'] }}"
    patterns: "*.conf"
    recurse: "{{ item['recurse'] | default(false) }}"
  loop: "{{ nginx_config_cleanup_paths }}"
  when: nginx_config_cleanup_paths is defined
  register: nginx_config_files

- name: Remove NGINX config files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ nginx_config_files['results'] | map(attribute='files') | sum(start=[]) | map(attribute='path') | list + nginx_config_cleanup_files | default('') | list }}"