---
# file : _template-config.yml
# description : generate nginx configuration file from template
# source : https://github.com/nginxinc/ansible-role-nginx-config/blob/main/tasks/config/template-config.yml

# - name: Configure NGINX modules
#   ansible.builtin.lineinfile:
#     path: /etc/nginx/nginx.conf
#     insertbefore: BOF
#     line: load_module {{ item }};
#   loop: "{{ nginx_config_modules }}"
#   when:
#     - nginx_config_modules is defined
#     - nginx_config_modules | length > 0

- name: Ensure NGINX main directory exists
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ nginx_config_main_template['deployment_location'] | default('/etc/nginx') | dirname }}"
    state: directory
    mode: "0755"
  when: nginx_config_main_template_enable | bool

- name: Dynamically generate NGINX main configuration file
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.template:
    src: "{{ nginx_config_main_template['template_file'] | default('nginx.conf.j2') }}"
    dest: "{{ nginx_config_main_template['deployment_location'] | default('/etc/nginx/nginx.conf') }}"
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    backup: "{{ nginx_config_main_template['backup'] | default(true) }}"
    mode: "0644"
  when: nginx_config_main_template_enable | bool

- name: Ensure NGINX client body cache directories exist
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ item['config']['core']['client_body_temp_path']['path'] }}"
    state: directory
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    mode: "0755"
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item['config']['core']['client_body_temp_path']['path'] | default('config[''core''][''client_body_temp_path''][''path''] undefined') }}" # noqa jinja[spacing]
  when:
    - nginx_config_http_template_enable | bool
    - item['config']['core']['client_body_temp_path']['path'] is defined

- name: Ensure NGINX proxy cache directories exist
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ item[1]['path'] }}"
    state: directory
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    mode: "0755"
  loop: "{{ nginx_config_http_template | subelements(['config', 'proxy', 'cache_path'], skip_missing=True) }}"
  loop_control:
    label: "{{ item[1]['path'] | default('config[''proxy''][''cache_path''][''path''] undefined') }}" # noqa jinja[spacing]
  when: nginx_config_http_template_enable | bool

- name: Ensure NGINX HTTP directory exists
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
    state: directory
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    mode: "0755"
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
  when: nginx_config_http_template_enable | bool

- name: Dynamically generate NGINX HTTP config files
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.template:
    src: "{{ item['template_file'] | default('http/default.conf.j2') }}"
    dest: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    backup: "{{ item['backup'] | default(true) }}"
    mode: "0644"
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
  when: nginx_config_http_template_enable | bool


- name: Ensure NGINX stream directory exists
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
    state: directory
    mode: "0755"
  loop: "{{ nginx_config_stream_template }}"
  loop_control:
    label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
  when: nginx_config_stream_template_enable | bool

- name: Dynamically generate NGINX stream config files
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.template:
    src: "{{ item['template_file'] | default('stream/default.conf.j2') }}"
    dest: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/stream_default.conf') }}"
    owner: "{{ nginx_configuration_user | default('nginx') }}"
    backup: true
    mode: "0644"
  loop: "{{ nginx_config_stream_template }}"
  loop_control:
    label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/stream_default.conf') }}"
  when: nginx_config_stream_template_enable | bool