---
# file : _upload-config.yml
# description : upload nginx assets
# source : https://github.com/nginxinc/ansible-role-nginx-config/blob/main/tasks/config/upload-config.yml

- name: Upload NGINX SSL certificates and keys
  when: nginx_config_upload_ssl_enable | bool
  block:
    - name: Ensure SSL certificate and key directories exist
      ansible.builtin.file:
        path: "{{ item['dest'] }}"
        state: directory
        mode: "0755"
      loop: "{{ nginx_config_upload_ssl_crt + nginx_config_upload_ssl_key }}"

    - name: Upload NGINX SSL certificates
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] | default('/etc/ssl/certs') }}"
        backup: "{{ item['backup'] | default(true) }}"
        mode: "0640"
      loop: "{{ nginx_config_upload_ssl_crt }}"

    - name: Upload NGINX SSL keys
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] | default('/etc/ssl/private') }}"
        backup: "{{ item['backup'] | default(true) }}"
        mode: "0640"
      loop: "{{ nginx_config_upload_ssl_key }}"
      no_log: true