---
# file : main.yml
# description : entrypoint for nginx configuration playbook
# source : https://github.com/nginxinc/ansible-role-nginx-config/blob/main/tasks/main.yml

- name: Cleanup NGINX config
  ansible.builtin.include_tasks: _cleanup-config.yml
  when: nginx_config_cleanup | bool
  tags: [nginx_config_cleanup]

- name: Upload NGINX config
  ansible.builtin.include_tasks: _upload-config.yml
  when: nginx_config_upload_ssl_enable | bool
  tags: [nginx_config_upload]

- name: Create NGINX config
  ansible.builtin.include_tasks: _template-config.yml
  when: nginx_config_main_template_enable | bool
        or nginx_config_http_template_enable | bool
        or nginx_config_stream_template_enable | bool
        or nginx_config_status_enable | bool
        or nginx_config_modules is defined and nginx_config_modules | length > 0
  tags: [nginx_config_template]

# - name: Debug output
#   ansible.builtin.include_tasks: "debug-output.yml"
#   when: nginx_config_debug_output | bool
#   tags: [nginx_config_debug_output]